### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by weijia-cheng** [EmmaSweeney/william-shakespeare_antony-and-cleopatra#1]
- [x] Erroneous `s` in `They are beaten, sir;s` in Act IV
- [x] [9.1.1.1](https://standardebooks.org/manual/1.6.2/9-metadata#9.11.4) says full names should include titles. I think the full name would be "Sir Lawrence Alma-Tadema" like in the colophon.
- [x] The `M.` in "M. Aemilius Lepidus" in the dramatis personae looks like an abbreviation

**Comment by weijia-cheng** [comment]
I think it should be `<abbr epub:type="z3998:given-name">M.</abbr>` since it stands for "Marcus"?

**Comment by EmmaSweeney** [comment]
Whoops! That should be fixed now.
